version: "3.4"

services:
    api:
        build:
          context: ./Backend
          dockerfile: Dockerfile
        ports:
          - "5000:80"
    frontend:
        build:
          context: ./Frontend
          dockerfile: Dockerfile
        ports:
          - "4200:4200"